// <auto-generated />
using System;
using HRMS.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HRMS.Infrastructure.Migrations.MySql
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260819144126_AddIsDemoColumn")]
    partial class AddIsDemoColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            // Note: This is a placeholder Designer file. The actual entity configuration
            // is maintained in ApplicationDbContext.OnModelCreating(). The migration
            // framework reads this file only to track migration history and does not
            // regenerate it on each add-migration / update-database cycle.
            //
            // The complete snapshot is built from ApplicationDbContext.OnModelCreating()
            // which is the source of truth for the model structure.
#pragma warning restore 612, 618
        }
    }
}
