#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# generate-secrets.sh
# Generates all required secrets for a fresh HRMS production deployment
# and writes them to .env (never committed — already in .gitignore).
#
# Phase 5: Updated from PostgreSQL to MySQL 8.4.
# POSTGRES_DB / POSTGRES_USER / POSTGRES_PASSWORD replaced with
# MYSQL_DATABASE / MYSQL_USER / MYSQL_PASSWORD / MYSQL_ROOT_PASSWORD.
#
# Usage:
#   chmod +x scripts/generate-secrets.sh
#   ./scripts/generate-secrets.sh
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/../.env"

if [[ -f "$ENV_FILE" ]]; then
  echo "⚠️  .env already exists. Delete it first if you want to regenerate secrets."
  exit 1
fi

echo "🔐 Generating secrets..."

# ── Symmetric secrets ──────────────────────────────────────────────────────
ENCRYPTION_KEY=$(openssl rand -base64 32)
# Use hex output instead of a filtering pipeline. With `set -o pipefail`,
# a filtering pipeline can fail when `head` closes early and the upstream
# process receives SIGPIPE.
MYSQL_PASSWORD=$(openssl rand -hex 14)
MYSQL_ROOT_PASSWORD=$(openssl rand -hex 14)
REDIS_PASSWORD=$(openssl rand -hex 14)
GRAFANA_PASS=$(openssl rand -hex 10)
BACKUP_KEY=$(openssl rand -base64 48)

# ── RSA-2048 key pair for JWT RS256 ───────────────────────────────────────
echo "🔑 Generating RSA-2048 key pair for JWT RS256..."

TMPDIR_RSA=$(mktemp -d)
trap 'rm -rf "$TMPDIR_RSA"' EXIT

openssl genrsa -out "${TMPDIR_RSA}/private.pem" 2048 2>/dev/null
openssl rsa -in "${TMPDIR_RSA}/private.pem" \
            -pubout -out "${TMPDIR_RSA}/public.pem" 2>/dev/null

JWT_PRIVATE_KEY_PEM=$(cat "${TMPDIR_RSA}/private.pem")
JWT_PUBLIC_KEY_PEM=$(cat "${TMPDIR_RSA}/public.pem")

# .env values must be single-line strings. Preserve PEM line boundaries as
# literal \n sequences; .NET normalizes them before importing the key.
JWT_PRIVATE_KEY_ENV=$(awk 'NF {printf "%s\\n", $0}' "${TMPDIR_RSA}/private.pem")
JWT_PUBLIC_KEY_ENV=$(awk 'NF {printf "%s\\n", $0}' "${TMPDIR_RSA}/public.pem")

# ── Write .env ─────────────────────────────────────────────────────────────
cat > "$ENV_FILE" << EOF
# ── Auto-generated by generate-secrets.sh — $(date -u '+%Y-%m-%d %H:%M UTC') ──
# DO NOT commit this file. It is listed in .gitignore.

# ── Database (MySQL 8.4) ───────────────────────────────────────────────────
MYSQL_DATABASE=hrms_db
MYSQL_USER=hrms
MYSQL_PASSWORD=${MYSQL_PASSWORD}
MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

# ── JWT RS256 key pair (auto-generated RSA-2048) ───────────────────────────
# Rotate quarterly or immediately on suspected compromise.
# To regenerate: delete .env and re-run this script, or run:
#   ./scripts/generate-rsa-keys.sh  (updates existing .env in-place)
Jwt__PrivateKeyPem=${JWT_PRIVATE_KEY_ENV}
Jwt__PublicKeyPem=${JWT_PUBLIC_KEY_ENV}

# ── PII Encryption (auto-generated AES-256 key) ─────────────────────────────
ENCRYPTION_KEY=${ENCRYPTION_KEY}
Security__EncryptionKey=${ENCRYPTION_KEY}
ConnectionStrings__DefaultConnection=Server=mysql;Port=3306;Database=hrms_db;User ID=hrms;Password=${MYSQL_PASSWORD};AllowPublicKeyRetrieval=True;SslMode=Required

# ── Redis (auto-generated) ──────────────────────────────────────────────────
REDIS_PASSWORD=${REDIS_PASSWORD}
REDIS_CONNECTION_STRING=redis:6379,password=${REDIS_PASSWORD},ssl=False,abortConnect=False

# ── Domain & nginx ───────────────────────────────────────────────────────────
# Used for: nginx.conf.template envsubst, AllowedHosts (.NET), email links.
# TODO: Replace yourdomain.com with your actual domain before deploying.
DOMAIN_NAME=yourdomain.com
API_URL=https://yourdomain.com/api
APP_ENV=production
SSL_CERT_PATH=/etc/letsencrypt/live/yourdomain.com/fullchain.pem
SSL_KEY_PATH=/etc/letsencrypt/live/yourdomain.com/privkey.pem

# ── .NET Host Filtering ──────────────────────────────────────────────────────
AllowedHosts=yourdomain.com

# ── Monitoring ───────────────────────────────────────────────────────────────
GRAFANA_ADMIN_USER=admin
GRAFANA_ADMIN_PASSWORD=${GRAFANA_PASS}

# ── Backup encryption ────────────────────────────────────────────────────────
BACKUP_ENCRYPTION_KEY=${BACKUP_KEY}

# ── CORS ────────────────────────────────────────────────────────────────────
# TODO: Set to your actual frontend domain(s), comma-separated.
ALLOWED_ORIGINS=https://yourdomain.com

# ── Email (SMTP) ────────────────────────────────────────────────────────────
# TODO: Fill in your SMTP credentials. Test with: scripts/test-email.sh
EMAIL_HOST=
EMAIL_PORT=587
EMAIL_USE_SSL=false
EMAIL_USERNAME=
EMAIL_PASSWORD=
EMAIL_FROM_ADDRESS=noreply@yourdomain.com
EMAIL_FROM_NAME=HRMS System
Email__Host=
Email__Port=587
Email__UseSsl=false
Email__Username=
Email__Password=
Email__FromAddress=noreply@yourdomain.com
Email__FromName=HRMS System

# ── App URL ─────────────────────────────────────────────────────────────────
# TODO: Set to your real domain. Used in password-reset emails.
APP_BASE_URL=https://yourdomain.com

# ── Branding ─────────────────────────────────────────────────────────────────────
# TODO: Replace with your actual company details. Used in email footers and Swagger UI.
APP_COMPANY_NAME=Your Company Name
APP_SUPPORT_NAME=Your Company HR Support
APP_SUPPORT_EMAIL=support@yourdomain.com

# ── Payroll ──────────────────────────────────────────────────────────────────
# State determines Professional Tax slabs. Options:
#   Maharashtra | Karnataka | WestBengal | TamilNadu | Telangana
#   AndhraPradesh | Gujarat | Punjab | Other (= ₹0 PT)
PAYROLL_DEFAULT_STATE=Other

# ── Monitoring (optional) ────────────────────────────────────────────────────
# Seq log server URL. Leave empty to disable remote log shipping.
# Self-hosted Seq is free for single-user. https://datalust.co/seq
SEQ_URL=

# ── Runtime ─────────────────────────────────────────────────────────────────
ASPNETCORE_ENVIRONMENT=Production

# IMPORTANT: Set to false after the first successful deploy.
# Run migrations manually from then on: scripts/migrate.sh
Database__AutoMigrate=false
EOF

chmod 600 "$ENV_FILE"

echo ""
echo "✅ .env created with generated secrets."
echo ""
echo "📋 Next steps:"
echo "   1. Edit .env — replace ALL 'yourdomain.com' with your real domain"
echo "      (DOMAIN_NAME, AllowedHosts, SSL_CERT_PATH, SSL_KEY_PATH, ALLOWED_ORIGINS)"
echo "      Also fill in: EMAIL_*, APP_BASE_URL"
echo "   2. Place TLS cert: ./nginx/ssl/cert.pem and ./nginx/ssl/key.pem"
echo "      (or run: sudo certbot certonly --standalone -d yourdomain.com)"
echo "   3. docker compose up -d"
echo "   4. Start the application once — SeedAsync prints the generated superadmin password to stdout."
echo "      Log in as superadmin@hrms.com with that password, then rotate it immediately in Settings."
echo "      There is no default hardcoded password. Do not attempt 'Admin@123'."
echo "   5. Migrations/backfill run through: docker compose run --rm migrate"
echo ""
echo "🔑 JWT key rotation: re-run this script (delete .env first) or run:"
echo "   ./scripts/generate-rsa-keys.sh   (updates JWT_PRIVATE_KEY_PEM / JWT_PUBLIC_KEY_PEM in-place)"
echo ""
